services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: yield_optimizer_bot
    env_file:
      - bot/.env
    depends_on:
      - postgres
    networks:
      - botnet

  postgres:
    image: postgres:17
    container_name: yield_optimizer_db
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: botpassword
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - botnet

volumes:
  postgres_data:

networks:
  botnet:

